import { createStore } from '../../shell/state.js';
import { createSceneSequencer } from '../../engine/sceneSequencer.js';
import { recordEnding } from '../../shell/save.js';
import * as questionnaireScene from '../../scenes/questionnaireScene.js';
import * as cutsceneScene from '../../scenes/cutsceneScene.js';
import * as dialogScene from '../../scenes/dialogScene.js';
import * as reckoningScene from '../../scenes/reckoningScene.js';
import * as endingScene from '../../scenes/endingScene.js';
import * as minigameScene from '../../scenes/minigameScene.js';
import { ANIMS } from './anims.js';
import { playStaticTransition } from '../../ui/staticTransition.js';

import itIntro from './content/it_intro.json';
import openingQuote from './content/opening_quote.json';
import bobBaiter from './content/bob_baiter.json';
import prologue from './content/prologue.json';
import therapist from './content/therapist.json';
import deborah from './content/deborah.json';
import rwanda from './content/rwanda.json';
import samun from './content/samun.json';
import rick from './content/rick.json';
import confrontDeborah from './content/confront_deborah.json';
import confrontRwanda from './content/confront_rwanda.json';
import confrontSamun from './content/confront_samun.json';
import confrontRick from './content/confront_rick.json';
import endings from './content/endings.json';

export const id = 'lake-ulysses';
export const title = 'Truth Debt: Lake Ulysses';

// The chapter is just this list, in order. `jumpTo` (see sceneSequencer.js)
// lets a dialog scene skip straight to 'reckoning' when Truth Debt maxes
// out mid-NPC. Adding a cutscene before an NPC, or a mini-game between two,
// is just another entry here — see docs/SCENE_TYPES.md.
//
// 'it-intro' is IT introducing itself — three class-neutral lines, before
// the player has a loadout or has seen a single swipe (docs/IT_DESIGN.md).
// It's its own scene, ahead of the opening call below, on purpose: IT is
// meant to be the very first thing that happens, full stop.
//
// Opening call (scenes 4-6) is one continuous unit, and the order matters:
// prologue's last beat is "Your phone buzzes against the gravel," so the
// questionnaire reads as answering that call and the therapist dialog as the
// same call continuing. Running questionnaire before prologue (as it did
// originally) fired the Therapist's diagnosis before the story established
// why she'd be talking to you at all. This shape is meant to be the routine
// chapter opener: you're on site, she buzzes in, she evaluates you.
//
// Each NPC now runs as explore -> confront -> encounter:
//   minigame   the walk to their door (art/captions still PLACEHOLDER,
//              generated by scripts/make-placeholder-room.mjs)
//   cutscene   the confrontation — you meet them face to face and pick how to
//              open. `opensDialog` + an option's `opener` write which node the
//              dialog scene starts on, so the choice shapes the encounter
//              instead of just decorating it (see cutsceneScene.js).
//   dialog     the encounter itself
// Therapist is exempt from all of it — she belongs to the opening call.
const SCENES = [
  { type: 'cutscene', id: 'it-intro', beats: itIntro.beats },
  { type: 'cutscene', id: 'opening-quote', beats: openingQuote.beats, anims: ANIMS },
  { type: 'cutscene', id: 'bob-baiter', beats: bobBaiter.beats, anims: ANIMS, ambient: '/assets/lake-ulysses/audio/lk_01.mp3' },
  { type: 'cutscene', id: 'prologue', beats: prologue.beats },
  { type: 'questionnaire', id: 'questionnaire' },
  { type: 'dialog', id: 'therapist', npc: therapist },

  { type: 'minigame', id: 'deborah-hallway', load: () => import('./minigames/deborah-hallway.js') },
  { type: 'cutscene', id: 'deborah-confront', beats: confrontDeborah.beats, opensDialog: 'deborah' },
  { type: 'dialog', id: 'deborah', npc: deborah },

  { type: 'minigame', id: 'rwanda-alley', load: () => import('./minigames/rwanda-alley.js') },
  { type: 'cutscene', id: 'rwanda-confront', beats: confrontRwanda.beats, opensDialog: 'rwanda' },
  { type: 'dialog', id: 'rwanda', npc: rwanda },

  { type: 'minigame', id: 'samun-garage', load: () => import('./minigames/samun-garage.js') },
  { type: 'cutscene', id: 'samun-confront', beats: confrontSamun.beats, opensDialog: 'samun' },
  { type: 'dialog', id: 'samun', npc: samun },

  { type: 'minigame', id: 'rick-barlot', load: () => import('./minigames/rick-barlot.js') },
  { type: 'cutscene', id: 'rick-confront', beats: confrontRick.beats, opensDialog: 'rick' },
  { type: 'dialog', id: 'rick', npc: rick },

  { type: 'reckoning', id: 'reckoning' },
  { type: 'ending', id: 'ending', endings },
];

const HANDLERS = {
  questionnaire: questionnaireScene,
  cutscene: cutsceneScene,
  dialog: dialogScene,
  reckoning: reckoningScene,
  ending: endingScene,
  minigame: minigameScene,
};

const initialRunState = {
  integrity: 5,
  trust: 5,
  stability: 5,
  lucidity: 5,
  truthDebt: 0,
  ledger: [],
  bloomsFired: [],
  lakeHealth: 1,
  loadout: 'Guns',
  // dialogSceneId -> node id, written by a confrontation cutscene's choice.
  openers: {},
};

export function mount(stageEl, { exit, startSceneId }) {
  const run = createStore(initialRunState);
  const sequencer = createSceneSequencer({
    scenes: SCENES,
    handlers: HANDLERS,
    context: { run, exit, recordEnding, chapterId: id },
    transitionFn: playStaticTransition,
    startSceneId,
  });

  sequencer.mount(stageEl);

  return function unmount() {
    sequencer.unmount();
  };
}
