import { createStore } from '../../shell/state.js';
import { takeDebugOverrides } from '../../shell/debug.js';
import { createSceneSequencer } from '../../engine/sceneSequencer.js';
import { recordEnding, saveCheckpoint, clearCheckpoint, loadSave } from '../../shell/save.js';
import { therapistReturnScene } from './therapistReturn.js';
import { registerCharacterArt } from '../../engine/characters.js';
import * as hud from '../../shell/hud.js';
import * as audio from '../../shell/audio.js';
import * as encounterMusic from '../../shell/encounterMusic.js';
import * as questionnaireScene from '../../scenes/questionnaireScene.js';
import * as cutsceneScene from '../../scenes/cutsceneScene.js';
import * as dialogScene from '../../scenes/dialogScene.js';
import * as reckoningScene from '../../scenes/reckoningScene.js';
import { forgetMeters } from '../../ui/statusBar.js';
import * as endingScene from '../../scenes/endingScene.js';
import * as minigameScene from '../../scenes/minigameScene.js';
import * as markerScene from '../../scenes/markerScene.js';
import { ANIMS } from './anims.js';
import { playStaticTransition } from '../../ui/staticTransition.js';

import itIntro from './content/it_intro.json';
import openingQuote from './content/opening_quote.json';
import bobBaiter from './content/bob_baiter.json';
import walkHome from './content/walk_home.json';
import prologue from './content/prologue.json';
import pastor from './content/pastor.json';
import feelzLaunch from './content/feelz_launch.json';
import therapist from './content/therapist.json';
import deborah from './content/deborah.json';
import rwanda from './content/rwanda.json';
import samun from './content/samun.json';
import rick from './content/rick.json';
import confrontDeborah from './content/confront_deborah.json';
import confrontRwanda from './content/confront_rwanda.json';
import confrontSamun from './content/confront_samun.json';
import confrontRick from './content/confront_rick.json';
import endings from './content/endings.json';

// Every character's drawn states (scripts/import-character-gifs.mjs writes these).
registerCharacterArt(import.meta.glob('./characters/*.json', { eager: true }));

export const id = 'lake-ulysses';
export const title = 'Truth Debt: Lake Ulysses';

// The chapter is just this list, in order. A full lake no longer cuts the
// chapter short: every NPC is met, and the debt picks the ending. Adding a cutscene before an NPC, or a mini-game between two,
// is just another entry here — see docs/SCENE_TYPES.md.
//
// 'it-intro' is IT introducing itself — three class-neutral lines, before
// the player has a loadout or has seen a single swipe (docs/IT_DESIGN.md).
// It's its own scene, ahead of the opening call below, on purpose: IT is
// meant to be the very first thing that happens, full stop.
//
// Opening call (scenes 4-6) is one continuous unit, and the order matters:
// prologue's last beat is "Your phone buzzes against the gravel," so the
// questionnaire reads as answering that call and the therapist dialog as the
// same call continuing. Running questionnaire before prologue (as it did
// originally) fired the Therapist's diagnosis before the story established
// why he'd be talking to you at all. This shape is meant to be the routine
// chapter opener: you're on site, he buzzes in, he evaluates you.
//
// Each NPC now runs as marker -> explore -> confront -> encounter:
//   marker     their page of the novel (scenes/markerScene.js): chapter,
//              numeral, a plate of their world, a few lines of prose, their
//              room's sound; the first step of the color code
//   minigame   the walk to their door (art/captions still PLACEHOLDER,
//              generated by scripts/make-placeholder-room.mjs)
//   cutscene   the confrontation — you meet them face to face and pick how to
//              open. `opensDialog` + an option's `opener` write which node the
//              dialog scene starts on, so the choice shapes the encounter
//              instead of just decorating it (see cutsceneScene.js). `npc`
//              lets each option show its first feeling's color.
//   dialog     the encounter itself
// Therapist is exempt from all of it — he belongs to the opening call.
const SCENES = [
  { type: 'cutscene', id: 'it-intro', beats: itIntro.beats },
  { type: 'cutscene', id: 'opening-quote', beats: openingQuote.beats, anims: ANIMS },
  { type: 'cutscene', id: 'bob-baiter', beats: bobBaiter.beats, anims: ANIMS, ambient: '/assets/lake-ulysses/audio/lk_01.mp3' },
  { type: 'cutscene', id: 'prologue', beats: prologue.beats },
  // The buzz from the prologue's last beat, answered: the FEELZ app opens,
  // and everything after it (intake quiz, Therapist, the HUD itself) is
  // happening inside that app.
  { type: 'cutscene', id: 'feelz-launch', beats: feelzLaunch.beats, unskippable: true },
  { type: 'questionnaire', id: 'questionnaire' },
  { type: 'dialog', id: 'therapist', npc: therapist },
  // The call ends and the player steps out into Lake Ulysses, walking home
  // to the building where the homework's neighbor lives.
  { type: 'cutscene', id: 'walk-home', beats: walkHome.beats },

  { type: 'marker', id: 'deborah-marker', numeral: 'I', npc: deborah, folio: 23,
    plate: "PLATE I. THE THIRD FLOOR.",
    prose: "The bulb over her door has been dying for months. Every night she stands under it with her key in her hand, and every night she does not reach up." },
  { type: 'minigame', id: 'deborah-hallway', load: () => import('./minigames/deborah-hallway.js'), npc: deborah },
  { type: 'cutscene', id: 'deborah-confront', beats: confrontDeborah.beats, opensDialog: 'deborah', npc: deborah },
  { type: 'dialog', id: 'deborah', npc: deborah },

  { type: 'marker', id: 'rwanda-marker', numeral: 'II', npc: rwanda, folio: 61,
    plate: "PLATE II. BEHIND THE STRIP.",
    prose: "Half a sign still lit, a payphone with its cord cut clean, and a wall somebody painted carefully, for nobody, and then somebody painted over." },
  { type: 'minigame', id: 'rwanda-alley', load: () => import('./minigames/rwanda-alley.js'), npc: rwanda },
  { type: 'cutscene', id: 'rwanda-confront', beats: confrontRwanda.beats, opensDialog: 'rwanda', npc: rwanda },
  { type: 'dialog', id: 'rwanda', npc: rwanda },

  { type: 'marker', id: 'samun-marker', numeral: 'III', npc: samun, folio: 97,
    plate: "PLATE III. THE GARAGE.",
    prose: "The bay door is up and nobody comes out. A radio plays to no station, and the calendar on the wall has been stuck on the same month for two years." },
  { type: 'minigame', id: 'samun-garage', load: () => import('./minigames/samun-garage.js'), npc: samun },
  { type: 'cutscene', id: 'samun-confront', beats: confrontSamun.beats, opensDialog: 'samun', npc: samun },
  { type: 'dialog', id: 'samun', npc: samun },

  { type: 'marker', id: 'rick-marker', numeral: 'IV', npc: rick, folio: 131,
    plate: "PLATE IV. THE LOT OUTSIDE THE BAR.",
    prose: "Gravel, six bikes, one door, and bass coming through the wall like a second heartbeat. Everyone inside already knows the sound of a stranger." },
  { type: 'minigame', id: 'rick-barlot', load: () => import('./minigames/rick-barlot.js'), npc: rick },
  { type: 'cutscene', id: 'rick-confront', beats: confrontRick.beats, opensDialog: 'rick', npc: rick },
  { type: 'dialog', id: 'rick', npc: rick },

  { type: 'reckoning', id: 'reckoning', pastor },
  { type: 'ending', id: 'ending', endings },
];

const HANDLERS = {
  questionnaire: questionnaireScene,
  cutscene: cutsceneScene,
  dialog: dialogScene,
  reckoning: reckoningScene,
  ending: endingScene,
  minigame: minigameScene,
  marker: markerScene,
};

const initialRunState = {
  integrity: 5,
  trust: 5,
  stability: 5,
  lucidity: 5,
  truthDebt: 0,
  // Lies in a row (a truth resets it): IT and SO cheer a streak on.
  lieStreak: 0,
  // His calls already made (dialogScene.js startCoach), and whether he has
  // explained the little screen on a call yet.
  coachSeen: [],
  scopeExplained: false,
  // How many of IT/SO's co-conspirator lines this run has used.
  cozySaid: 0,
  ledger: [],
  bloomsFired: [],
  lakeHealth: 1,
  loadout: 'Guns',
  // dialogSceneId -> node id, written by a confrontation cutscene's choice.
  openers: {},
  // dialogSceneId -> true: your class restored something in their room
  // (ui/walkRoom.js), so their confrontation offers the secret opener.
  secrets: {},
  // { [emotion]: count } — every FEELZ pick across the whole run, keyed by
  // emotion name. Drives the dominant-emotion IT interrupt at the end of
  // each NPC encounter (engine/loadout.js's getDominantEmotion()).
  emotionCounts: {},
  // { [nodeId]: 'truth' | 'lie' } — how each dialog node was answered.
  // Read by npc.outro conditions (the Therapist's homework sign-off).
  choices: {},
  // What IT/SO last "found" (engine/itFindings.js): which way the last
  // leaning encounter went, and the last dominant emotion they read out.
  // They only speak again when one of these changes.
  itLastSide: null,
  itLastLean: undefined,
  // The FEELZ check-in answers ({ water, fine } → the chosen label), set by
  // feelz_launch.json's `record` options. The ending reads them back against
  // what the player actually did (endingScene.js).
  checkIn: {},
  // Trust built with each NPC ({ [npc]: { syncs, bids } }, engine/trust.js;
  // not `trust`, which is the TRU meter), and the feelings unlocked during
  // the run beyond the class's starting three.
  bonds: {},
  // { [npc]: emotion } — which feeling each NPC gave (engine/unlocks.js).
  giftedBy: {},
  // Which pace comments IT/SO have already made this run ({ fast, skim }).
  pressureSaid: {},
  // A feeling unlocked as an encounter ended, waiting to make its entrance
  // on the next encounter's wheel (dialogScene.js).
  pendingFresh: null,
  // { [nodeId]: the line the player said } — IT quotes contradictions back.
  said: {},
  unlocked: [],
  // The FEELZ evaluation's read on the player (questionnaireScene.js), said
  // by the therapist as he looks over the intake (therapist_01 {intake}).
  intakeRead: null,
  // NPCs whose story (their STORY cutscene) the player has heard.
  storiesHeard: [],
  // Each baptism card's answer, in order ('confess' | 'down'), for the
  // repeat client's file (endingScene.js saves it as save.lastRun).
  reckoningChoices: [],
  // A player who has finished this chapter before: the Therapist reads last
  // run's file and asks whether to check in (TIPS) and rerun the tutorial.
  repeat: false,
};

// For the settings panel's DEBUG page: every scene, in order.
export const DEBUG_SCENES = SCENES.map(({ id, type }) => ({ id, type }));

export function mount(stageEl, { exit, restart, startSceneId }) {
  forgetMeters(); // a new run: no meter "changes" carried over from the last one
  // Played it before: the Therapist recognizes you instead of teaching you
  // (therapistReturn.js), and stays quiet for the rest of the run.
  const lastRun = loadSave().lastRun;
  const repeatState = lastRun ? { repeat: true, scopeExplained: true } : {};
  const run = createStore({ ...initialRunState, ...repeatState, ...takeDebugOverrides() });
  // Repeat client: his "you again" call takes the 'therapist' slot, with the
  // full tutorial right after it for a player who asks to run it again.
  const scenes = run.get().repeat && lastRun
    ? SCENES.flatMap((s) => (s.id === 'therapist' ? [therapistReturnScene(lastRun), { ...s, id: 'therapist-tutorial' }] : [s]))
    : SCENES;
  const sequencer = createSceneSequencer({
    scenes,
    handlers: HANDLERS,
    context: { run, exit, recordEnding, chapterId: id },
    transitionFn: playStaticTransition,
    startSceneId,
    // Keeps the HUD's fast-forward icon (shell/hud.js) in sync with whether
    // the *current* scene has anything safe to skip — see sceneSequencer.js's
    // isSkippable() for which scene types that is.
    onSceneChange: (scene) => {
      hud.setSkip(sequencer.isSkippable() ? sequencer.skip : null);
      // Checkpoint at the start of every scene (shell/save.js): a crash loses
      // at most the scene in progress. An ending means the run is done.
      if (scene.type === 'ending') clearCheckpoint();
      else if (saveCheckpoint({ chapterId: id, sceneId: scene.id, state: run.get() })) hud.showSaving();
    },
  });

  hud.setChapterActive({ onRestart: restart });
  sequencer.mount(stageEl);

  return function unmount() {
    hud.setChapterActive(null);
    hud.setSkip(null);
    sequencer.unmount();
    // Leaving mid-confrontation must not leave an NPC's music behind.
    encounterMusic.end({ fade: 0.3 });
    audio.stopLeitmotif();
    audio.unhush(0.05);
  };
}
